
services:
  # Config Server
  configsvr:
    image: mongo:latest
    container_name: configsvr
    command: --configsvr --replSet configReplSet --port 27019
    ports:
      - 27019:27019
    volumes:
      - ./data/configdb:/data/db:Z

  # Shard 1
  shard1:
    image: mongo:latest
    container_name: shard1
    command: --shardsvr --replSet shard1ReplSet --port 27018
    ports:
      - 27018:27018
    volumes:
      - ./data/shard1:/data/db:Z

  # Shard 2
  shard2:
    image: mongo:latest
    container_name: shard2
    command: --shardsvr --replSet shard2ReplSet --port 27018
    ports:
      - 27028:27018
    volumes:
      - ./data/shard2:/data/db:Z

  # Shard 3
  shard3:
    image: mongo:latest
    container_name: shard3
    command: --shardsvr --replSet shard3ReplSet --port 27018
    ports:
      - 27038:27018
    volumes:
      - ./data/shard3:/data/db:Z

  # Shard 4
  shard4:
    image: mongo:latest
    container_name: shard4
    command: --shardsvr --replSet shard4ReplSet --port 27018
    ports:
      - 27048:27018
    volumes:
      - ./data/shard4:/data/db:Z

  # Mongos (Router)
  mongos:
    image: mongo:latest
    container_name: mongos
    command: mongos --configdb configReplSet/configsvr:27019 --port 27017
    ports:
      - 27017:27017
    depends_on:
      - configsvr
      - shard1
      - shard2
      - shard3
      - shard4